@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}


### Health check
GET {{host}}/health  HTTP/1.1

### Login
# @name login
POST {{host}}/login/v1/auth/login  HTTP/1.1
Content-Type: application/json

{
  "email": "antipan.pablo@gmail.com",
  "password": "qweqwe123"
}

###
@token = {{login.response.body.token}}

### Create a new player
POST {{host}}/api/v1/players  HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe",
  "age": 25,
  "position": "Midfielder",
  "rating": 23
}





